### ISSUE TITLE
Что делают эти две строчки?

### ISSUE THREAD

**Issue by HOCOnbIPKA** [SOURUS/Reverse_Ray_Tracing#1]
Здравствуйте Александр, подскажите пожалуйста, что делают эти две строчки?
// Проверка на пересечение луча с полигоном
		for (int q = 0; q < num; q++)
		{
			if(q != n)
			{
				check_crossfire = objects[q].A*ray.x + objects[q].B*ray.y + objects[q].C*ray.z; *вот эта
				if (check_crossfire != 0)
				{
					crossfire =-(objects[q].A*camera.x + objects[q].B*camera.y + objects[q].C*camera.z + objects[q].D)/check_crossfire; *и вот эта
					find.change(camera.x+ray.x*crossfire,camera.y+ray.y*crossfire,camera.z+ray.z*crossfire);
					if (Hit(q,find) != 0)
					{
						cross_mas[count].change(find.x,find.y,find.z);
						cross_mas[count].number = q; //какой полигон пересекли
						count++;
					}
				}
			}
		}

**Comment by SOURUS** [comment]
Привет, Илья.

Дело было давно, но попытаюсь вспомнить.

Первая строка, которая тебя интересует, проверяет есть ли вообьще пересечение пересечение Линии с Треугольником (эт причем формула была из учебника по Алгебре) (почему треугольник и что за формула, к сожалению не вспомню)

Вторая строка уже просчитывает в каком месте она (линия = луч в нашем случае) пересеклась с поверхностью.

Вроде как-то так :)

вторая строка

**Comment by HOCOnbIPKA** [comment]
Спасибо
